# Generated by Django 2.0 on 2018-09-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniurl',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrementttt"),
        ),
    ]
