# Generated by Django 2.0 on 2018-09-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url_app', '0003_auto_20180913_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=31)),
                ('moyenne', models.IntegerField(default=10)),
            ],
        ),
    ]
