# Generated by Django 2.0 on 2018-10-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url_app', '0005_lieu_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miniurl',
            options={'permissions': (('commenter_article', 'Commenter un article'), ('marquer_article', 'Marquer un article comme lu')), 'verbose_name': '< Mini URL >', 'verbose_name_plural': '< Minis URL >'},
        ),
    ]
